// when errors are thrown, the entire callstack is logged
function addOne(num) {

